version: '3.8'
services:
  server:  # Not "client"—this is the Wasp server
      build:
        context: ./app  # Point to app/ where wasp build runs
        dockerfile: .wasp/out/Dockerfile
      ports:
        - "3001:3001"
      environment:
        - postgresql://postgresWaspDevUser:postgresWaspDevPass@localhost:5432/OpenSaaS-76afe7a55f
        - PORT=3001
      depends_on:
        - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgresWaspDevUser
      - POSTGRES_PASSWORD=postgresWaspDevPass
      - POSTGRES_DB=OpenSaaS-76afe7a55f
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

volumes:
  pgdata: