version: '3.8'

services:
  # Local PostgreSQL for development
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase_dev 
      POSTGRES_DB: metabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  
  metabase:
    build:
      context: ../metabase  
      dockerfile: ../docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../configs/metabase.env  # secrets
    volumes:
      - metabase-data:/metabase-data
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl -f http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-data:
  metabase-data: